package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.BaseCatalog2;
import com.datu.fanli.bean.BaseCatalog2Example;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author: datu
 * @date: 2020/1/15
 */
public interface BaseCatalog2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseCatalog2SqlProvider.class, method="countByExample")
    long countByExample(BaseCatalog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BaseCatalog2SqlProvider.class, method="deleteByExample")
    int deleteByExample(BaseCatalog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_base_catalog2",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_base_catalog2 (name, catalog1_id)",
        "values (#{name,jdbcType=VARCHAR}, #{catalog1Id,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(BaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @InsertProvider(type=BaseCatalog2SqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(BaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseCatalog2SqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog1_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<BaseCatalog2> selectByExample(BaseCatalog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, catalog1_id",
        "from pms_base_catalog2",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog1_id", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    BaseCatalog2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog2SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BaseCatalog2 record, @Param("example") BaseCatalog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog2SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BaseCatalog2 record, @Param("example") BaseCatalog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog2SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BaseCatalog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog2
     *
     * @mbg.generated
     */
    @Update({
        "update pms_base_catalog2",
        "set name = #{name,jdbcType=VARCHAR},",
          "catalog1_id = #{catalog1Id,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BaseCatalog2 record);
}