package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.BaseAttrInfo;
import com.datu.fanli.bean.BaseAttrInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author: datu
 * @date: 2020/1/15
 */
public interface BaseAttrInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseAttrInfoSqlProvider.class, method="countByExample")
    long countByExample(BaseAttrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BaseAttrInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(BaseAttrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_base_attr_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_base_attr_info (attr_name, catalog3_id, ",
        "is_enabled)",
        "values (#{attrName,jdbcType=VARCHAR}, #{catalog3Id,jdbcType=BIGINT}, ",
        "#{isEnabled,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(BaseAttrInfo record);

    /**
     * 已设置id插入
     * @param record
     * @return
     */
    @Insert({
            "insert into pms_base_attr_info (id, value_name, attr_id, ",
            "is_enabled)",
            "values (#{id, jdbcType=BIGINT}, #{valueName,jdbcType=VARCHAR}, #{attrId,jdbcType=BIGINT}, ",
            "#{isEnabled,jdbcType=VARCHAR})"
    })
    int insertWithId(BaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @InsertProvider(type=BaseAttrInfoSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(BaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseAttrInfoSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="attr_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="is_enabled", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<BaseAttrInfo> selectByExample(BaseAttrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, attr_name, catalog3_id, is_enabled",
        "from pms_base_attr_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="attr_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="is_enabled", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    BaseAttrInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseAttrInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BaseAttrInfo record, @Param("example") BaseAttrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseAttrInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BaseAttrInfo record, @Param("example") BaseAttrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseAttrInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BaseAttrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Update({
        "update pms_base_attr_info",
        "set attr_name = #{attrName,jdbcType=VARCHAR},",
          "catalog3_id = #{catalog3Id,jdbcType=BIGINT},",
          "is_enabled = #{isEnabled,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BaseAttrInfo record);

    /**
     * 改变属性值启用状态
     * @param id 属性值id
     * @param isEnabled 是否启用
     * @return 成功码
     */
    @Update({
            "update pms_base_attr_info",
            "set is_enabled = #{isEnabled,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int changeAttrInfoStatus(String id, String isEnabled);
}