package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.BaseSaleAttr;
import com.datu.fanli.bean.BaseSaleAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BaseSaleAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseSaleAttrSqlProvider.class, method="countByExample")
    long countByExample(BaseSaleAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BaseSaleAttrSqlProvider.class, method="deleteByExample")
    int deleteByExample(BaseSaleAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_base_sale_attr",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_base_sale_attr (name, catalog3_id)",
        "values (#{name,jdbcType=VARCHAR}, #{catalog3Id,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(BaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @InsertProvider(type=BaseSaleAttrSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(BaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseSaleAttrSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    List<BaseSaleAttr> selectByExample(BaseSaleAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, catalog3_id",
        "from pms_base_sale_attr",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    BaseSaleAttr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseSaleAttrSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BaseSaleAttr record, @Param("example") BaseSaleAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseSaleAttrSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BaseSaleAttr record, @Param("example") BaseSaleAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseSaleAttrSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BaseSaleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @Update({
        "update pms_base_sale_attr",
        "set name = #{name,jdbcType=VARCHAR},",
          "catalog3_id = #{catalog3Id,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BaseSaleAttr record);
}