package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.BaseCatalog1;
import com.datu.fanli.bean.BaseCatalog1Example;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BaseCatalog1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseCatalog1SqlProvider.class, method="countByExample")
    long countByExample(BaseCatalog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BaseCatalog1SqlProvider.class, method="deleteByExample")
    int deleteByExample(BaseCatalog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_base_catalog1",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_base_catalog1 (name)",
        "values (#{name,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(BaseCatalog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @InsertProvider(type=BaseCatalog1SqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(BaseCatalog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @SelectProvider(type=BaseCatalog1SqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<BaseCatalog1> selectByExample(BaseCatalog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name",
        "from pms_base_catalog1",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    BaseCatalog1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog1SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BaseCatalog1 record, @Param("example") BaseCatalog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog1SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BaseCatalog1 record, @Param("example") BaseCatalog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BaseCatalog1SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BaseCatalog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_catalog1
     *
     * @mbg.generated
     */
    @Update({
        "update pms_base_catalog1",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BaseCatalog1 record);
}