package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.ProductInfo;
import com.datu.fanli.bean.ProductInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=ProductInfoSqlProvider.class, method="countByExample")
    long countByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ProductInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_product_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_product_info (product_name, description, ",
        "catalog3_id, tm_id)",
        "values (#{productName,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{catalog3Id,jdbcType=BIGINT}, #{tmId,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @InsertProvider(type=ProductInfoSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @SelectProvider(type=ProductInfoSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="product_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="tm_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    List<ProductInfo> selectByExample(ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, product_name, description, catalog3_id, tm_id",
        "from pms_product_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="product_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="description", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="catalog3_id", javaType=Long.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="tm_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    ProductInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @Update({
        "update pms_product_info",
        "set product_name = #{productName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "catalog3_id = #{catalog3Id,jdbcType=BIGINT},",
          "tm_id = #{tmId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ProductInfo record);
}