package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.ProductVerifyRecord;
import com.datu.fanli.bean.ProductVerifyRecordExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author: datu
 * @date: 2020/1/15
 */
public interface ProductVerifyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @SelectProvider(type=ProductVerifyRecordSqlProvider.class, method="countByExample")
    long countByExample(ProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ProductVerifyRecordSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_product_verify_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_product_verify_record (product_id, create_time, ",
        "vertify_man, status, ",
        "detail)",
        "values (#{productId,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{vertifyMan,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{detail,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(ProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @InsertProvider(type=ProductVerifyRecordSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(ProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @SelectProvider(type=ProductVerifyRecordSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="product_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="vertify_man", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="detail", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<ProductVerifyRecord> selectByExample(ProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, product_id, create_time, vertify_man, status, detail",
        "from pms_product_verify_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="product_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="create_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="vertify_man", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="detail", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    ProductVerifyRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductVerifyRecordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductVerifyRecord record, @Param("example") ProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductVerifyRecordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductVerifyRecord record, @Param("example") ProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ProductVerifyRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbg.generated
     */
    @Update({
        "update pms_product_verify_record",
        "set product_id = #{productId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "vertify_man = #{vertifyMan,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "detail = #{detail,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ProductVerifyRecord record);
}