package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.SkuAttrValue;
import com.datu.fanli.bean.SkuAttrValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SkuAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuAttrValueSqlProvider.class, method="countByExample")
    long countByExample(SkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SkuAttrValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_sku_attr_value",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_sku_attr_value (attr_id, value_id, ",
        "sku_id)",
        "values (#{attrId,jdbcType=BIGINT}, #{valueId,jdbcType=BIGINT}, ",
        "#{skuId,jdbcType=BIGINT})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @InsertProvider(type=SkuAttrValueSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(SkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuAttrValueSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="attr_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="value_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="sku_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    List<SkuAttrValue> selectByExample(SkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, attr_id, value_id, sku_id",
        "from pms_sku_attr_value",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=String.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="attr_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="value_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="sku_id", javaType=String.class, jdbcType=JdbcType.BIGINT)
    })
    SkuAttrValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuAttrValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SkuAttrValue record, @Param("example") SkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuAttrValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SkuAttrValue record, @Param("example") SkuAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuAttrValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SkuAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_attr_value
     *
     * @mbg.generated
     */
    @Update({
        "update pms_sku_attr_value",
        "set attr_id = #{attrId,jdbcType=BIGINT},",
          "value_id = #{valueId,jdbcType=BIGINT},",
          "sku_id = #{skuId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SkuAttrValue record);
}