package com.datu.fanli.manage.dao;

import com.datu.fanli.bean.SkuImage;
import com.datu.fanli.bean.SkuImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SkuImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuImageSqlProvider.class, method="countByExample")
    long countByExample(SkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SkuImageSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pms_sku_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pms_sku_image (sku_id, img_name, ",
        "img_url, product_img_id, ",
        "is_default)",
        "values (#{skuId,jdbcType=BIGINT}, #{imgName,jdbcType=VARCHAR}, ",
        "#{imgUrl,jdbcType=VARCHAR}, #{productImgId,jdbcType=BIGINT}, ",
        "#{isDefault,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @InsertProvider(type=SkuImageSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(SkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @SelectProvider(type=SkuImageSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="sku_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="img_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="img_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="product_img_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="is_default", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<SkuImage> selectByExample(SkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, sku_id, img_name, img_url, product_img_id, is_default",
        "from pms_sku_image",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Long.class, jdbcType=JdbcType.BIGINT, id=true),
        @Arg(column="sku_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="img_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="img_url", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="product_img_id", javaType=String.class, jdbcType=JdbcType.BIGINT),
        @Arg(column="is_default", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    SkuImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuImageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SkuImage record, @Param("example") SkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuImageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SkuImage record, @Param("example") SkuImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SkuImageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SkuImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Update({
        "update pms_sku_image",
        "set sku_id = #{skuId,jdbcType=BIGINT},",
          "img_name = #{imgName,jdbcType=VARCHAR},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "product_img_id = #{productImgId,jdbcType=BIGINT},",
          "is_default = #{isDefault,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SkuImage record);
}