package com.datu.fanli.bean;

import java.io.Serializable;

public class BaseSaleAttr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_sale_attr.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_sale_attr.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_sale_attr.catalog3_id
     *
     * @mbg.generated
     */
    private String catalog3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    public BaseSaleAttr(String id, String name, String catalog3Id) {
        this.id = id;
        this.name = name;
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    public BaseSaleAttr() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_sale_attr.id
     *
     * @return the value of pms_base_sale_attr.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_sale_attr.id
     *
     * @param id the value for pms_base_sale_attr.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_sale_attr.name
     *
     * @return the value of pms_base_sale_attr.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_sale_attr.name
     *
     * @param name the value for pms_base_sale_attr.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_sale_attr.catalog3_id
     *
     * @return the value of pms_base_sale_attr.catalog3_id
     *
     * @mbg.generated
     */
    public String getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_sale_attr.catalog3_id
     *
     * @param catalog3Id the value for pms_base_sale_attr.catalog3_id
     *
     * @mbg.generated
     */
    public void setCatalog3Id(String catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_sale_attr
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append("]");
        return sb.toString();
    }
}