package com.datu.fanli.bean;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;

public class BaseAttrValue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.id
     *
     * @mbg.generated
     */
    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.value_name
     *
     * @mbg.generated
     */
    @Column
    private String valueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.attr_id
     *
     * @mbg.generated
     */
    @Column
    private String attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_value.is_enabled
     *
     * @mbg.generated
     */
    @Column
    private String isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    public BaseAttrValue(String id, String valueName, String attrId, String isEnabled) {
        this.id = id;
        this.valueName = valueName;
        this.attrId = attrId;
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    public BaseAttrValue() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.id
     *
     * @return the value of pms_base_attr_value.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.id
     *
     * @param id the value for pms_base_attr_value.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.value_name
     *
     * @return the value of pms_base_attr_value.value_name
     *
     * @mbg.generated
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.value_name
     *
     * @param valueName the value for pms_base_attr_value.value_name
     *
     * @mbg.generated
     */
    public void setValueName(String valueName) {
        this.valueName = valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.attr_id
     *
     * @return the value of pms_base_attr_value.attr_id
     *
     * @mbg.generated
     */
    public String getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.attr_id
     *
     * @param attrId the value for pms_base_attr_value.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(String attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_value.is_enabled
     *
     * @return the value of pms_base_attr_value.is_enabled
     *
     * @mbg.generated
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_value.is_enabled
     *
     * @param isEnabled the value for pms_base_attr_value.is_enabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_value
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", valueName=").append(valueName);
        sb.append(", attrId=").append(attrId);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append("]");
        return sb.toString();
    }
}