package com.datu.fanli.bean;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

public class BaseAttrInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.id
     *
     * @mbg.generated
     */
    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    @Column
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    @Column
    private String catalog3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    @Column
    private String isEnabled;

    @Transient
    private List<BaseAttrValue> attrValueList;

    public List<BaseAttrValue> getAttrValueList() {
        return attrValueList;
    }

    public void setAttrValueList(List<BaseAttrValue> attrValueList) {
        this.attrValueList = attrValueList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    public BaseAttrInfo(String id, String attrName, String catalog3Id, String isEnabled) {
        this.id = id;
        this.attrName = attrName;
        this.catalog3Id = catalog3Id;
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    public BaseAttrInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.id
     *
     * @return the value of pms_base_attr_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.id
     *
     * @param id the value for pms_base_attr_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.attr_name
     *
     * @return the value of pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.attr_name
     *
     * @param attrName the value for pms_base_attr_info.attr_name
     *
     * @mbg.generated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.catalog3_id
     *
     * @return the value of pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    public String getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.catalog3_id
     *
     * @param catalog3Id the value for pms_base_attr_info.catalog3_id
     *
     * @mbg.generated
     */
    public void setCatalog3Id(String catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_base_attr_info.is_enabled
     *
     * @return the value of pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_base_attr_info.is_enabled
     *
     * @param isEnabled the value for pms_base_attr_info.is_enabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_base_attr_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", attrName=").append(attrName);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append("]");
        return sb.toString();
    }
}