package com.datu.fanli.bean;

import java.util.ArrayList;
import java.util.List;

public class ProductSaleAttrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public ProductSaleAttrExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdIsNull() {
            addCriterion("sale_attr_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdIsNotNull() {
            addCriterion("sale_attr_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdEqualTo(String value) {
            addCriterion("sale_attr_id =", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdNotEqualTo(String value) {
            addCriterion("sale_attr_id <>", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdGreaterThan(String value) {
            addCriterion("sale_attr_id >", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr_id >=", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdLessThan(String value) {
            addCriterion("sale_attr_id <", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdLessThanOrEqualTo(String value) {
            addCriterion("sale_attr_id <=", value, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdIn(List<String> values) {
            addCriterion("sale_attr_id in", values, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdNotIn(List<String> values) {
            addCriterion("sale_attr_id not in", values, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdBetween(String value1, String value2) {
            addCriterion("sale_attr_id between", value1, value2, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrIdNotBetween(String value1, String value2) {
            addCriterion("sale_attr_id not between", value1, value2, "saleAttrId");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameIsNull() {
            addCriterion("sale_attr_name is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameIsNotNull() {
            addCriterion("sale_attr_name is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameEqualTo(String value) {
            addCriterion("sale_attr_name =", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameNotEqualTo(String value) {
            addCriterion("sale_attr_name <>", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameGreaterThan(String value) {
            addCriterion("sale_attr_name >", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr_name >=", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameLessThan(String value) {
            addCriterion("sale_attr_name <", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameLessThanOrEqualTo(String value) {
            addCriterion("sale_attr_name <=", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameLike(String value) {
            addCriterion("sale_attr_name like", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameNotLike(String value) {
            addCriterion("sale_attr_name not like", value, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameIn(List<String> values) {
            addCriterion("sale_attr_name in", values, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameNotIn(List<String> values) {
            addCriterion("sale_attr_name not in", values, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameBetween(String value1, String value2) {
            addCriterion("sale_attr_name between", value1, value2, "saleAttrName");
            return (Criteria) this;
        }

        public Criteria andSaleAttrNameNotBetween(String value1, String value2) {
            addCriterion("sale_attr_name not between", value1, value2, "saleAttrName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}