package com.datu.fanli.bean;

import java.io.Serializable;

public class ProductSaleAttr implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.sale_attr_id
     *
     * @mbg.generated
     */
    private String saleAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_sale_attr.sale_attr_name
     *
     * @mbg.generated
     */
    private String saleAttrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public ProductSaleAttr(String id, String productId, String saleAttrId, String saleAttrName) {
        this.id = id;
        this.productId = productId;
        this.saleAttrId = saleAttrId;
        this.saleAttrName = saleAttrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    public ProductSaleAttr() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.id
     *
     * @return the value of pms_product_sale_attr.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.id
     *
     * @param id the value for pms_product_sale_attr.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.product_id
     *
     * @return the value of pms_product_sale_attr.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.product_id
     *
     * @param productId the value for pms_product_sale_attr.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.sale_attr_id
     *
     * @return the value of pms_product_sale_attr.sale_attr_id
     *
     * @mbg.generated
     */
    public String getSaleAttrId() {
        return saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.sale_attr_id
     *
     * @param saleAttrId the value for pms_product_sale_attr.sale_attr_id
     *
     * @mbg.generated
     */
    public void setSaleAttrId(String saleAttrId) {
        this.saleAttrId = saleAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_sale_attr.sale_attr_name
     *
     * @return the value of pms_product_sale_attr.sale_attr_name
     *
     * @mbg.generated
     */
    public String getSaleAttrName() {
        return saleAttrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_sale_attr.sale_attr_name
     *
     * @param saleAttrName the value for pms_product_sale_attr.sale_attr_name
     *
     * @mbg.generated
     */
    public void setSaleAttrName(String saleAttrName) {
        this.saleAttrName = saleAttrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_sale_attr
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", saleAttrId=").append(saleAttrId);
        sb.append(", saleAttrName=").append(saleAttrName);
        sb.append("]");
        return sb.toString();
    }
}