package com.datu.fanli.bean;

import javax.persistence.Transient;
import java.io.Serializable;
import java.util.List;

public class ProductInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.catalog3_id
     *
     * @mbg.generated
     */
    private String catalog3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_info.tm_id
     *
     * @mbg.generated
     */
    private String tmId;

    @Transient
    private List<ProductImage> productImageList;

    @Transient
    private List<ProductSaleAttr> productSaleAttrList;

    public List<ProductImage> getProductImageList() {
        return productImageList;
    }

    public void setProductImageList(List<ProductImage> productImageList) {
        this.productImageList = productImageList;
    }

    public List<ProductSaleAttr> getProductSaleAttrList() {
        return productSaleAttrList;
    }

    public void setProductSaleAttrList(List<ProductSaleAttr> productSaleAttrList) {
        this.productSaleAttrList = productSaleAttrList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    public ProductInfo(String id, String productName, String description, String catalog3Id, String tmId) {
        this.id = id;
        this.productName = productName;
        this.description = description;
        this.catalog3Id = catalog3Id;
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    public ProductInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.id
     *
     * @return the value of pms_product_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.id
     *
     * @param id the value for pms_product_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.product_name
     *
     * @return the value of pms_product_info.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.product_name
     *
     * @param productName the value for pms_product_info.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.description
     *
     * @return the value of pms_product_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.description
     *
     * @param description the value for pms_product_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.catalog3_id
     *
     * @return the value of pms_product_info.catalog3_id
     *
     * @mbg.generated
     */
    public String getCatalog3Id() {
        return catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.catalog3_id
     *
     * @param catalog3Id the value for pms_product_info.catalog3_id
     *
     * @mbg.generated
     */
    public void setCatalog3Id(String catalog3Id) {
        this.catalog3Id = catalog3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_info.tm_id
     *
     * @return the value of pms_product_info.tm_id
     *
     * @mbg.generated
     */
    public String getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_info.tm_id
     *
     * @param tmId the value for pms_product_info.tm_id
     *
     * @mbg.generated
     */
    public void setTmId(String tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productName=").append(productName);
        sb.append(", description=").append(description);
        sb.append(", catalog3Id=").append(catalog3Id);
        sb.append(", tmId=").append(tmId);
        sb.append("]");
        return sb.toString();
    }
}