package com.datu.fanli.bean;

import java.io.Serializable;

public class SkuImage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.img_name
     *
     * @mbg.generated
     */
    private String imgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    private String productImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_image.is_default
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    public SkuImage(Long id, String skuId, String imgName, String imgUrl, String productImgId, String isDefault) {
        this.id = id;
        this.skuId = skuId;
        this.imgName = imgName;
        this.imgUrl = imgUrl;
        this.productImgId = productImgId;
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    public SkuImage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.id
     *
     * @return the value of pms_sku_image.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.id
     *
     * @param id the value for pms_sku_image.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.sku_id
     *
     * @return the value of pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.sku_id
     *
     * @param skuId the value for pms_sku_image.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.img_name
     *
     * @return the value of pms_sku_image.img_name
     *
     * @mbg.generated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.img_name
     *
     * @param imgName the value for pms_sku_image.img_name
     *
     * @mbg.generated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.img_url
     *
     * @return the value of pms_sku_image.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.img_url
     *
     * @param imgUrl the value for pms_sku_image.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.product_img_id
     *
     * @return the value of pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    public String getProductImgId() {
        return productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.product_img_id
     *
     * @param productImgId the value for pms_sku_image.product_img_id
     *
     * @mbg.generated
     */
    public void setProductImgId(String productImgId) {
        this.productImgId = productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_image.is_default
     *
     * @return the value of pms_sku_image.is_default
     *
     * @mbg.generated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_image.is_default
     *
     * @param isDefault the value for pms_sku_image.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", skuId=").append(skuId);
        sb.append(", imgName=").append(imgName);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", productImgId=").append(productImgId);
        sb.append(", isDefault=").append(isDefault);
        sb.append("]");
        return sb.toString();
    }
}